name: Setup env

on:
  workflow_call:

jobs:
  setup-macos:
    runs-on: macos-latest
    env:
      SCCACHE_GHA_ENABLED: "true"
      RUSTC_WRAPPER: "sccache"
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
            toolchain: "1.77"
            override: true
      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.3
      - name: Build
        run: cargo build
      - name: Cache build
        uses: actions/cache/save@v4
        with:
          key: ${{ github.sha }}-setup-macos
          path: |
            ~/.cargo
  
